### ISSUE TITLE
add_taxon.py issue

### ISSUE THREAD

**Issue by hverbruggen** [rbturnbull/orthoflow#68]
Starting to test on some real datasets and the workflow dies early on:

Error message:
```
[Wed Sep  7 23:19:56 2022]
rule add_taxon:
    input: results/intake/Myriotrichia-clavaeformis_MALE_CDS-gff.cds.fa
    output: results/intake/taxon-added/Myriotrichia-clavaeformis_MALE_CDS-gff.cds.fasta
    jobid: 110
    reason: Missing output files: results/intake/taxon-added/Myriotrichia-clavaeformis_MALE_CDS-gff.cds.fasta; Input files updated by another job: results/intake/Myriotrichia-clavaeformis_MALE_CDS-gff.cds.fa
    wildcards: source=Myriotrichia-clavaeformis_MALE_CDS-gff
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/a82b8e93a2cfd15c40543d680610686d
Traceback (most recent call last):
  File "/home/ubuntu/phaeoexplorer/input_data/phyloflow/phyloflow/workflow/scripts/add_taxon.py", line 4, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
[Wed Sep  7 23:19:56 2022]
Error in rule add_taxon:
    jobid: 107
    output: results/intake/taxon-added/Myriotrichia-clavaeformis_FEMALE_CDS-gff.cds.fasta
    conda-env: /home/ubuntu/phaeoexplorer/input_data/.snakemake/conda/a82b8e93a2cfd15c40543d680610686d
    shell:
        python /home/ubuntu/phaeoexplorer/input_data/phyloflow/phyloflow/workflow/scripts/add_taxon.py --unique-counter Myriotrichia_clavaeformis results/intake/Myriotrichia-clavaeformis_FEMALE_CDS-gff.cds.fa results/intake/taxon-added/Myriotrichia-clavaeformis_FEMALE_CDS-gff.cds.fasta
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Traceback (most recent call last):
  File "/home/ubuntu/phaeoexplorer/input_data/phyloflow/phyloflow/workflow/scripts/add_taxon.py", line 4, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
```

**Comment by rbturnbull** [comment]
This is fixed now.
